POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title" : "Title of the task",
  "date" : "2025-01-01T12:00:00Z",
  "description" : "Ini adalah deskrispi yang ada di dalam task, berisikan apa saja yang akan dilakukan",
  "priority" : "normal",
  "status": "todo" 
}