GET http://localhost:3001/some.text

GET http://localhost:3001/post
GET http://localhost:3001/posts 

GET http://localhost:3001/tag 
GET http://localhost:3001/tagss 
GET http://localhost:3001/tags 

GET http://localhost:3001/error/404 
GET http://localhost:3001/error/403

GET http://localhost:3001/dragonfly
GET http://localhost:3001/fly
GET http://localhost:3001/flybird

